### ISSUE TITLE
Admin felületen jóváírás gomb irányítson át

### ISSUE THREAD

**Issue by HegeMte** [bprof-projm/foerum#143]
Elsonek probaljuk megoldani iframe-vel, hogy az link tartalmat megjelenítjuk egy iframeben 
ha ez nem megy akkor a gomb-y redirect megoldas

gomb megnyomása erre a linkre irányítson át:
https://testnet.bscscan.com/token/0xa0e11ca7c99655c6ca16336f1af69b6a7683fdfc

**Comment by conoren** [comment]
done. not with iframe, but with new tab
