### ISSUE TITLE
Get and give back all topics from a subject with an endpoint

### ISSUE THREAD

**Issue by devv77** [bprof-projm/foerum#90]

**Comment by devv77** [comment]
#115 #87 #90 ezekkel a jegyekkel mia a helyzet? In reviewba ragadtak? Ment róla a PR vagy várunk itt még valamire? Gondolom kész vannak, miért vannak még itt?

**Comment by IIB3nceII** [comment]
Ezeknek a kovetese es atrakasa annak a feladata aki a taskot csinlata, mi a vegen donebol kiszedjuk ha kell
